### PR TITLE
Update cip-0002.md

### PR DESCRIPTION
**Pull request by deweller**
Move cip-2 to accepted

### CODE REVIEW

**Comment by jdogresorg** [comment]
ACK

**Comment by CounterpartyMatt** [comment]
ACK

**Comment by trevorxcp** [comment]
ACK

**Comment by rubensayshi** [comment]
ACK

**Comment by cointea1121** [comment]
ACK. Sorry about the late response guys.

**Comment by robby-dermody** [comment]
ACK

**Pull request merged**
