### PR TITLE
Added CIP-4

### PR DESCRIPTION
**Pull request by jdogresorg**
Subassets

### CODE REVIEW

**Comment by deweller** [comment]
@jdogresorg 

Here are a few questions and points that I think might make this CIP clearer.

1. You allow lowercase letters and numbers in sub-assets while all the examples are all uppercase letters and dashes.  Is this intentional?  if so, consider adding some examples

2. Subasset can only be issued from same address __that owns the__ parent asset __at the time of the issuance__.  (My suggestions in __bold__).

3. Can you add a Rationale?  Why are subassets needed?  Why is this single level solution preferable to a multi level hierarchy?

4. I am a bit confused when reading the 4 steps in the Issuances section.  `issuance.initialize` seems like something done in the counterparty-lib code base one time as part of the migration to the new standards.  `validate` and `compose` are steps that happen every time in an issuance transaction.  And `validate` and `parse` should happen during any parse/reparse of transactions.  Is that correct?  If so, I think this section could use a little more explanation.  Perhaps you can break the steps up into `issuance` and `validate/parse` sections.  And perhaps move the initialize piece into a section about code changes required (or remove the initialize piece altogether).

**Comment by adamkrellenstein** [comment]
Makes sense to me! I'd like to see mocked API calls, though (just the relevant fields) for the steps for issuing 1) an asset 2) a subasset.

**Comment by jdogresorg** [comment]
Updated CIP to include API examples. 

When first issuing a subasset, the full asset name (asset_longname) would be specified in the "asset" field. All further issuances for that subasset would have the "asset" field set to the random numeric asset.

**Comment by droplister** [comment]
Interesting proposal, J-Dog. It's a different design than I thought, but it's easier to understand now that it's laid out as a CIP. It's like a protocol on top of a protocol on top of a protocol. We must go deeper...

**Am I understanding this correctly?**
This is basically a way allow a source address the ability to issue numeric assets, but with aliases.

That alias gets set inside of an issuance message, similar to how Counterparty puts data inside of a   bitcoin transaction. This change proposes storing data inside the description of your numeric asset. I think technically that's possible already, but with these changes it makes it part of the protocol. Cool! 

The restriction on asset_longname, that makes it a subasset, is that:
`THEFIRSTPART.of.a.period.separated.string.MUST.BE.equal.to.an.ASSET.owned.by.the.source.address`

**Finding parents and children?**
Having a not null asset_longname is the flag that indicates it as a subasset, right?

Is there a need for a flag like “has_subassets” similar to “divisibility” or “locked” on parent assets? Or would you just perform a search on asset_longname for all subassets, and then look at the first part of the strings, and work up from there? Can numeric assets have subassets?

**Updating subasset descriptions**
I am also little confused around asset descriptions too. How would you update your subasset description in this scenario? At the time of issuance when an asset name contains a period (.) the Counterparty protocol will validate the subasset name and ownership, create a random numeric asset with the description containing the asset_longname hex. And Counterparty will track these numeric assets with special descriptions using the “asset_longname” column on the assets table.

But Counterparty adds the hex right? When I am updating a description, it will already contain a hex, so will Counterparty append a hex, remove a hex, validate the existing hex?

I am not a Python coder, but I think `description.split('3b3b')` could be tricked if I put a hex inside of my description. It might be better to look at the description starting from the right. Using `rpartitions('3b3b') `or `rsplit('3b3b',1)`? Again, not a Python coder.

**Out of consensus subassets**

What if I just issue a regular numeric asset with the description:
`Dominos pizza is really good 3b3b6C50495a5a412e444f4d494e4f53`

**What if I want to lock my subasset?**

I think right now, you have to make your description = LOCK to lock an asset. That would basically render a subasset no longer a subasset?

**Valid name requirements**
I have some questions regarding what is a valid subasset name considering the existing protocol specification for a valid asset name differs on a few points.

Existing: Unique, 4-12 Latin characters, Uppercase, not beginning with A.
Proposal: Non-unique, 1-250 Alphanumeric + [.-_@!], periods as separators only.

Can these specifications be reconciled at all?

For some of the reasons, I would prefer a change to what constitutes a valid name rather than relying on numeric asset descriptions and the asset_longname column.

**Comment by jdogresorg** [comment]
>Am I understanding this correctly?

Yes. Except it sounds like you believe the encoded hex data needs to stay tacked on to the description and carried forward in future updates. This is not the case. The encoded hex data is automatically created/appended/removed/validated by counterparty when needed. You treat the description field exactly as you did before.

>Having a not null asset_longname is the flag that indicates it as a subasset, right?

Correct.

>Is there a need for a flag like “has_subassets” similar to “divisibility” or “locked” on parent assets? Or would you just perform a search on asset_longname for all subassets, and then look at the first part of the strings, and work up from there? 

I plan on updating counterpartychain.io with subasset support, so I can provide some APIs to return a list of subassets/children, etc.

>Can numeric assets have subassets?

No. Only named assets can have subassets.

>It might be better to look at the description starting from the right.
>Using rpartitions('3b3b')or rsplit('3b3b',1).

Good suggestion. CIP updated :)

>What if I just issue a regular numeric asset with the description from the address that owns PIZZA: 
>Dominos pizza is really good 3b3b6C50495a5a412e444f4d494e4f53

This brings up a good point, I have added some additional validation rules to the CIP to ensure that the asset_longname field is only set on the initial issuance.

>When I am updating a description, it will already contain a hex, so will Counterparty append a hex, remove a hex, validate the existing hex?

The description will NOT contain a hex. The hex encoded data is tacked onto the user-specified description automatically, during the first issuance, and is used to indicate the longname.

You will never see the hex encoded data in the description, as it is only in the issuance transaction.

>What if I want to lock my subasset?

You can lock the supply of a subasset.

>Can this be implemented as a change to valid asset names?

No. I believe this would require a massive overhaul.

**Comment by robby-dermody** [comment]
Let's close of discussion on this CIP in 2 weeks (by April 1, unless major issues are found) and slate it for implementation.

**Comment by droplister** [comment]
NACK

If this is about to be closed to discussion and move to final implementation, I'd like to go on the record as being against this, at least as implemented here.

I think y'all will move ahead, since it's obviously something people annoyed with "stagnation" in XCP want and I don't believe in veto power (as if I had any real say in things), but I think _very little thought_ went into the **naming conventions** as defined above.

Some suggestions, for the record:

1. Make it 0.5 XCP to issue a subasset.
I don't see any reason to reduce the fee, if the fee exists as a spam prevention mechanism why lower the bar at all? It's not like subassets are any less powerful than assets or use up less UTXOs or fewer database entries.

1. Only allow for 1 level deep.
Ex: THIS.THAT - More levels could be added later, if there was demand, but I don't really see that demand right now. My PoV is that Counterparty is a financial innovation and that names are like stock symbols or something. There are cases of STOCK.A and STOCK.B, but no instances of STOCK.what.do.we.need.this@for.really.

1. Only allow 1-12 Latin characters, Uppercase.
This is just to be inline with the existing naming rules. The current design of this CIP makes asset names much more like urls or email addresses rather than subdomains or something like subdomains. But I feel like the point that is missed is that assets in XCP aren't just names. The name is just the most visible part of the iceberg. I think it's important to keep XCP assets recognizable as XCP assets. With as much variance as is on the table, I don't think you'll be able to readily identify these strings as XCP assets. I think it's valuable to be able to look at a string and know what to do with it. "http://" is what works for URLs. "www." is what works for domains. We don't have anything like that in Counterparty, and the design here goes even further down the road of unrecognizability which impacts usability, ultimately. 


I think numeric assets continue to provide the incredible flexibility you might expect to come out of this subasset change, but we don't see people really using numeric assets this way, so...

Well, that's my final 2 cents on it.

**Comment by deweller** [comment]
Thanks @droplister.  Please note that accepting a CIP is no guarantee that the CIP will be adopted or code will be merged to support it.  Another author might submit a competing CIP that solves the problem of subassets.

After a CIP is merged in draft status, it will be accepted or rejected at some point in the future.  For a Standards Track CIP to move from draft to accepted status, it must have code that implements it.

Comments here are to let the author(s) have a chance to hear the community opinion and to modify the proposal if desired.  So your feedback is valuable.

Unless there are any fatal flaws or errors found with this CIP, it will be merged on Friday, April 1st in draft status.

**Comment by droplister** [comment]
I see. I'm such a n00b! I'm now informed better. Cheers! I still stand by what I said though.

**Pull request merged**
