### PR TITLE
- Added support for taproot cip

### PR DESCRIPTION
**Pull request by pataegrillo**

### CODE REVIEW

**Review by Jpja — CHANGES_REQUESTED** [review]
A good proposal. Only a few things before merging:

1. Why not broaden the CIP to include native segwit multisig (bc1q)? The motivation of this upgrade imo should be to make Counterparty compatible with all main address formats.

2. Which exact prefix will taproot address use in the message data (hex and decimal)?

3. How many bytes is the encoded taproot address? As far as I remember a standard address takes up a 1 byte prefix + 20 bytes. I guess from the CIP I can deduct that since "the memo must be 12 bytes less in size", the taproot address takes up 1+32 bytes.

4. The discussion of less space for memo assumes op_return encoding, right? To fit those 80 bytes you must shorten the memo BUT you can use another encoding if you really want to have a long memo, correct?

5. Good that library compatibility is discussed. Whether or not to add taproot before an update to the main library will need some discussion BUT this CIP is regardless very good :)

**Comment by jdogresorg** [comment]
The work is done on this and a PR is ready to merge into Counterparty-lib.

Let’s keep discussions in the discussion area n not question ppl about their design decisions to try to get ppl to change their CIP in a PR.

imo this should be merged… it’s a proposal, not code that needs to be perfect before merging.

**Comment by Jpja** [comment]
The motivation is that taproot's popularity has increased. We need numbers. How many percent of addresses use taproot? Which wallets? Are taproot addresses more popular than native segwit multisig, which are also not supported?

Both taproot and native segwit multisig change Counterparty's encoding assumption of a fixed address length of 1+20 bytes, so adding one of these is technically not much more difficult than adding both. Support for both naturally falls under the same CIP imo.

Also, I suspect that "the memo must be 12 bytes less in size" holds true only if op_return encoding is used. This should be clarified.

**Comment by jdogresorg** [comment]
So proposals won’t be merged until your happy with all the details of the proposal?

Maybe I am taking things too personal but seems like ANY improvement or proposal to change CP is met with resistance and more “we should do X” conversations… and little to no progress is made…. we are supposed to have a process for moving from idea to discussions to proposal to code, and it’s worked fine until recently.

Look at the CIPs and improvements over  the past 3-4 years, almost all were proposed and coded by John, Javier, and myself… the most progress was made when the coders are allowed to code and not spend their time defending their ideas repeatedly at every step of the process… that is what the CIP discussion phase is for.

now look at the last 6-12 months, lots of drama, lots of opinions, any updates or improvements have been attacked, consistently, even months after code has been merged (CIP03)…. It is exhausting and  demoralizing.

I know your intention is good, and you want the best for CP, but IMO this is making proposing and implementing ideas more difficult.

I encourage you to re-read cip01 and reconsider your actions. If after reading cip01, you feel your fulfilling you job as CIP editor, I’ll accept that we have different understandings of the role.

I support you as CIP Editor either way, just pointing out that we’re already a small community with an even smaller dev community. The more friction/resistance there is in the process, the less ideas n code will flow…

**Comment by jotapea** [comment]
> The work is done on this and a PR is ready to merge into Counterparty-lib.

Why was this worked on before doing a CIP? Was there $ involved in the work done?

**Comment by jotapea** [comment]
Considering the CIP by itself, I am in the camp of not requiring the latest version of Bitcoin Core to run Counterparty. This proposal would mean that counterparty-lib will require Bitcoin Core v24 as the minimum version, right? At the moment the minimum version of Bitcoin required for counterparty-lib is lower, I'm running v0.21.1 but I think a couple of lower versions should still work.

Finding these lowest compatible versions should be part of this conversation. I believe that Counterparty's strength is in its legacy and working with older versions of Bitcoin honors this legacy.

**Pull request merged**
