### PR TITLE
Cip 9 memo format

### PR DESCRIPTION
**Pull request by deweller**
Here's my rationale for these proposed changes:

+ **Memo** is a more recognizable term in the cryptocurrency space than payment ID.  Since we are allowing text here, we should not swim upstream.
+ Let's store the memo as compact binary data, but allow support input and output as both hex and utf-8 strings.  That way users can choose.  We weren't going to support LIKE queries in the API anyway.
+ I removed data for the number of destinations and replaced it with memo length data.  I moved the memo before the destinations.  This way, with destinations last, we can have an arbitrary number of destinations.  Storj's use case, for example, will be to include more than 256 recipients in a single transaction.
+ I split the memo length byte into 3 bits for the multi-send format and 5 bits for the payment ID length.  This allows us the flexibility for 7 different multi-send configurations if we need them (I think we will only need 2).

### CODE REVIEW

**Comment by jdogresorg** [comment]
This looks good to me. @loon @rubensayshi @robby-dermody Thoughts?

**Comment by loon3** [comment]
Format Flags definition is inconsistent.

Initially it mentions that it includes 3 parameters..
(Multisend Format + Memo Format + Memo Length) 

the example only shows 2...
(Multisend Format + Memo Length)

**Comment by deweller** [comment]
I removed the extraneous Memo format reference.

**Comment by deweller** [comment]
@loon3 - Can you ACK/NOACK or comment on this?  Tnx.

**Comment by loon3** [comment]
My only comment would be what I brought up in Slack; is it worth it to increase the maximum memo length at the expense of the number of multi-send types.  

Currently it's 3 bits for the multi-send format (8 options) and 5 bits for the memo length (32 options, is this 0 to 31 or 1 to 32 for character length?).  We could also do 2/6 bits which is 4 options for multi-send but it also doubles the memo length.

That being said, I think it's probably fine.  If no one else has an opinion, then ACK

**Comment by robby-dermody** [comment]
In line with my comments on slack I think CIP9 needs a bit more talk/discussion, especially on how we will extend the message format (or if we will make a new format) for the upcoming multisend/CIP10.This matters in CIP9 because we have a few fields which are "reserved" for multisend use, where either we need to finalize on them or remove them, based on the following discussion around what the multisend feature will look like:

* I think one path for multisend is rather simple, where you have a single asset, single memo, and allow for N destination addresses and amounts
* I think this would work well for maybe 70-80% of uses. the other path is more complex and comprehensive: you can have a separate asset, dest address, amount and memo for each address
* that will cover all cases, but adds complexity to the UI and at the protocol level (where it also leads to a bit larger tx)
* everything else seems to be a bit of an arbitrary mix between these two

**Comment by loon3** [comment]
I don't think it's necessary to finalize CIP10 before starting work on CIP9.  

Determining multi-send types and what's important (what to include, what not to include) will be a much bigger discussion than whether we should add a memo field and move the destination address to the counterparty message.

**Comment by deweller** [comment]
With loon3's ACK, I'm merging these changes.

Noted that this CIP might be influenced by what we decide to do for multisends.    We can start discussing the multisends CIP in a separate thread and adjust here if needed.

**Pull request merged**
